; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
board_build.psram = enable

build_flags =
    -DBOARD_HAS_PSRAM
    -DPSRAM_ENABLE=1
    -DLWIP_TCP_MSS=1460
    -DLWIP_TCP_SND_BUF=8192
    -DLWIP_TCP_WND=8192
    -DLWIP_TCP_RCV_BUF=8192
    -DLWIP_SO_RCVTIMEO=1
    -DLWIP_IP_ACCEPT_UDP_PORT=0
    -DLWIP_TCP_NODELAY=1
    -DLWIP_TCP_KEEPALIVE=1
    -DLWIP_TCP_KEEPIDLE=30
    -DLWIP_TCP_KEEPINTVL=15
    -DLWIP_TCP_KEEPCNT=5
    -DARDUINO_LOOP_STACK_SIZE=8192
    -DCONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    -DCONFIG_ESP_TASK_WDT_EN=0
