[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_flags =
    -DLWIP_TCP_MSS=1460
    -DLWIP_TCP_SND_BUF=8192
    -DLWIP_TCP_WND=8192
    -DLWIP_TCP_RCV_BUF=8192
    -DLWIP_SO_RCVTIMEO=1
    -DLWIP_IP_ACCEPT_UDP_PORT=0
    -DLWIP_TCP_NODELAY=1
    -DLWIP_TCP_KEEPALIVE=1
    -DLWIP_TCP_KEEPIDLE=30
    -DLWIP_TCP_KEEPINTVL=15
    -DLWIP_TCP_KEEPCNT=5
    -DARDUINO_LOOP_STACK_SIZE=8192
    -DCONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    -DCONFIG_ESP_TASK_WDT_EN=0
